// Code generated by Wire protocol buffer compiler, do not edit.
package routeguide

import io.grpc.CallOptions
import io.grpc.Channel
import io.grpc.stub.AbstractStub
import io.grpc.stub.ClientCalls.asyncBidiStreamingCall
import io.grpc.stub.ClientCalls.asyncClientStreamingCall
import io.grpc.stub.ClientCalls.asyncServerStreamingCall
import io.grpc.stub.ClientCalls.asyncUnaryCall
import io.grpc.stub.StreamObserver

public class RouteGuideWireGrpc {
  public fun newStub(channel: Channel): RouteGuideStub = RouteGuideStub(channel)

  /**
   * Interface exported by the server.
   *
   * Defined in src/test/proto/RouteGuideProto.proto
   */
  public class RouteGuideStub : AbstractStub<RouteGuideStub> {
    internal constructor(channel: Channel) : super(channel)

    internal constructor(channel: Channel, callOptions: CallOptions) : super(channel, callOptions)

    override fun build(channel: Channel, callOptions: CallOptions): RouteGuideStub = RouteGuideStub(channel, callOptions)

    /**
     * A simple RPC.
     *
     * Obtains the feature at a given position.
     *
     * A feature with an empty name is returned if there's no feature at the given
     * position.
     *
     * Defined in src/test/proto/RouteGuideProto.proto
     */
    public fun GetFeature(request: Point, response: StreamObserver<Feature>) {
      asyncUnaryCall(channel.newCall(getGetFeatureMethod(), callOptions), request, response)
    }

    /**
     * A server-to-client streaming RPC.
     *
     * Obtains the Features available within the given Rectangle.  Results are
     * streamed rather than returned at once (e.g. in a response message with a
     * repeated field), as the rectangle may cover a large area and contain a
     * huge number of features.
     *
     * Defined in src/test/proto/RouteGuideProto.proto
     */
    public fun ListFeatures(request: Rectangle, response: StreamObserver<Feature>) {
      asyncServerStreamingCall(channel.newCall(getListFeaturesMethod(), callOptions), request, response)
    }

    /**
     * A client-to-server streaming RPC.
     *
     * Accepts a stream of Points on a route being traversed, returning a
     * RouteSummary when traversal is completed.
     *
     * Defined in src/test/proto/RouteGuideProto.proto
     */
    public fun RecordRoute(response: StreamObserver<RouteSummary>): StreamObserver<Point> = asyncClientStreamingCall(channel.newCall(getRecordRouteMethod(), callOptions), response)

    /**
     * A Bidirectional streaming RPC.
     *
     * Accepts a stream of RouteNotes sent while a route is being traversed,
     * while receiving other RouteNotes (e.g. from other users).
     *
     * Defined in src/test/proto/RouteGuideProto.proto
     */
    public fun RouteChat(response: StreamObserver<RouteNote>): StreamObserver<RouteNote> = asyncBidiStreamingCall(channel.newCall(getRouteChatMethod(), callOptions), response)
  }
}
