name: gradle-wrapper

on:
  pull_request:
    paths:
    - 'gradlew'
    - 'gradlew.bat'
    - 'gradle/wrapper/'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4 # v1

